#!/bin/bash

#activate anvio
conda activate anvio-8

# Loop through all .fna files in the current directory
for file in *.fna; do
    # Extract the base name of the file (without extension)
    base_name=$(basename "$file" .fna)
    
    # Generate the output file name
    output_file="${base_name}.fasta"
    
    # Run the anvi-script-reformat-fasta command
    anvi-script-reformat-fasta "$file" -o "$output_file" --simplify-names
    
    echo "Processed: $file -> $output_file"
done
